//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClimbFind.Web.Mvc.Controls.AdUnits {
    
    
    public partial class IndoorPlaceDetailsRight160x600 {
    }
}
