//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClimbFind.Web.Mvc.Views.Home {
    
    
    public partial class IndexAuthenticated {
        
        /// <summary>
        /// FeedUC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IdentityStuff.Views.CFFeed.Feed FeedUC;
        
        /// <summary>
        /// PostToFeedTxB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IdentityStuff.Views.CFFeed.PlaceGoingClimbingTxB PostToFeedTxB;
    }
}
