//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityStuff.Views.Moderate {
    
    
    public partial class AddAreaTag {
        
        /// <summary>
        /// NationalityDDLUC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ClimbFind.Web.UI.Controls.DropDownLists.NationalityDDL NationalityDDLUC;
        
        /// <summary>
        /// NameTxB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PeterBlum.VAM.TextBox NameTxB;
        
        /// <summary>
        /// NameVAL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ClimbFind.Web.Mvc.Controls.Validators.FullName NameVAL;
        
        /// <summary>
        /// ParagraphNameTxB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PeterBlum.VAM.TextBox ParagraphNameTxB;
        
        /// <summary>
        /// ParagraphNameVAL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ClimbFind.Web.Mvc.Controls.Validators.FullName ParagraphNameVAL;
        
        /// <summary>
        /// SavePlaceBtN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PeterBlum.VAM.LinkButton SavePlaceBtN;
    }
}
