//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityStuff.Views.Moderate {
    
    
    public partial class EditOutdoorLocation {
        
        /// <summary>
        /// NameLb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label NameLb;
        
        /// <summary>
        /// ShortNameTxB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ShortNameTxB;
        
        /// <summary>
        /// LatitudeTxB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PeterBlum.VAM.DecimalTextBox LatitudeTxB;
        
        /// <summary>
        /// LongitudeTxB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PeterBlum.VAM.DecimalTextBox LongitudeTxB;
        
        /// <summary>
        /// AreaTxB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IdentityStuff.Views.Moderate.AreaTagForCountryTxB AreaTxB;
        
        /// <summary>
        /// AddAreaLkB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PeterBlum.VAM.LinkButton AddAreaLkB;
        
        /// <summary>
        /// AreaTagsLV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DataList AreaTagsLV;
        
        /// <summary>
        /// DescriptionTxB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PeterBlum.VAM.TextBox DescriptionTxB;
        
        /// <summary>
        /// DirectionsTxB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PeterBlum.VAM.TextBox DirectionsTxB;
        
        /// <summary>
        /// AccommodationTxB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PeterBlum.VAM.TextBox AccommodationTxB;
        
        /// <summary>
        /// FoodTxB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PeterBlum.VAM.TextBox FoodTxB;
        
        /// <summary>
        /// LocalBetaTxB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PeterBlum.VAM.TextBox LocalBetaTxB;
        
        /// <summary>
        /// SavePlaceBtN control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PeterBlum.VAM.LinkButton SavePlaceBtN;
    }
}
